### PR TITLE
Add gha docker

### PR DESCRIPTION
**Pull request by Firefishy**

### CODE REVIEW

**Comment by Firefishy** [comment]
An example build: https://github.com/Firefishy/switch2osm-mkdocs/actions/runs/5123151413/jobs/9213251837

**Comment by Andygol** [comment]
Here is 403 erroe code

https://github.com/Firefishy/switch2osm-mkdocs/actions/runs/5123151413/jobs/9213251837#step:7:712

**Comment by Firefishy** [comment]
Permission issue fixed now.

**Comment by Andygol** [comment]
Hmm, I noticed that your run was successful according to the following link: https://github.com/Firefishy/switch2osm-mkdocs/actions/runs/5123525388.

However, despite the successful run, I still see the "Merge pull request" button on my side is inactive.

@Firefishy, I would appreciate your thoughts and input on this matter.

**Pull request closed without merging**
